name: 'Preview update'

on:
  pull_request:
    types: [synchronize]

env:
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_docker_url: ${{ secrets.DOCKER_URL }}
  TF_VAR_docker_username: ${{ secrets.DOCKER_USERNAME }}
  TF_VAR_docker_password: ${{ secrets.DOCKER_PASSWORD }}
  TF_VAR_tag: ${{ github.sha }}

jobs:
  build_app:
    name: 'Build App'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      name: Build App docker image
      with:
        login-server: ${{ secrets.DOCKER_URL }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        cd demo-app
        docker build -t ${{ secrets.DOCKER_URL }}/demo-app:${{ github.sha }} .
        docker tag ${{ secrets.DOCKER_URL }}/demo-app:${{ github.sha }} ${{ secrets.DOCKER_URL }}/demo-app:pr$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        docker push ${{ secrets.DOCKER_URL }}/demo-app

  terraform:
    name: 'Update'
    needs: [build_app]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.25

    - name: Terraform Format
      id: fmt
      run: terraform fmt
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform select Workspace
      id: workspace
      run: terraform workspace select "ephemeral-$GITHUB_HEAD_REF"

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Taint database
      id: taint_db
      run: terraform taint azurerm_sql_database.sql_database

    - name: Terraform Apply
      run: terraform apply -auto-approve

  e2e:
    name: 'E2E'
    needs: [build_app, terraform]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.25
        terraform_wrapper: false
    - name: Terraform Init
      id: init
      working-directory: ./infrastructure
      run: terraform init

    - name: Terraform select Workspace
      id: workspace
      working-directory: ./infrastructure
      run: terraform workspace select "ephemeral-$GITHUB_HEAD_REF"

    - name: Get App URL
      id: app
      working-directory: ./infrastructure
      run: echo ::set-output name=value::$(terraform output -json -no-color app | jq -r '.hostname')

    - name: 'Setup Node.js'
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: NPM cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Tests
      id: tests
      continue-on-error: true
      working-directory: ./demo-app
      run: ng e2e --devServerTarget="" --base-url={{ steps.app.output.value }}